// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApk3Vtb8ENCCfBg5o3Cye65dvx47yPDkw',
    appId: '1:201087510979:web:9bc7c207dfd07b2df33576',
    messagingSenderId: '201087510979',
    projectId: 'first-project-6f0fb',
    authDomain: 'first-project-6f0fb.firebaseapp.com',
    storageBucket: 'first-project-6f0fb.appspot.com',
    measurementId: 'G-7YVDREGRD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs1CJrb6qKng7PUzB_blH8oJ8bJkxdYPI',
    appId: '1:201087510979:android:9c9433e88c807bb6f33576',
    messagingSenderId: '201087510979',
    projectId: 'first-project-6f0fb',
    storageBucket: 'first-project-6f0fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoPjyd9LUsl3VxG7OmUGXlzRqxeXhhkbk',
    appId: '1:201087510979:ios:9df8a8dbe4903ed2f33576',
    messagingSenderId: '201087510979',
    projectId: 'first-project-6f0fb',
    storageBucket: 'first-project-6f0fb.appspot.com',
    iosClientId: '201087510979-ap14vmboag3vdhucuemscrp5udaf8v3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.fairebaseCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoPjyd9LUsl3VxG7OmUGXlzRqxeXhhkbk',
    appId: '1:201087510979:ios:9df8a8dbe4903ed2f33576',
    messagingSenderId: '201087510979',
    projectId: 'first-project-6f0fb',
    storageBucket: 'first-project-6f0fb.appspot.com',
    iosClientId: '201087510979-ap14vmboag3vdhucuemscrp5udaf8v3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.fairebaseCli',
  );
}
